class CoreException(Exception):
    pass


class UserAlreadyExists(CoreException):
    pass
